package Model;
// Generated 27-mar-2014 13:26:20 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private short empNo;
     private String apellido;
     private String oficio;
     private Short dir;
     private Date fechaAlt;
     private Long salario;
     private Long comision;
     private Byte deptNo;

    public Emp() {
    }

	
    public Emp(short empNo) {
        this.empNo = empNo;
    }
    public Emp(short empNo, String apellido, String oficio, Short dir, Date fechaAlt, Long salario, Long comision, Byte deptNo) {
       this.empNo = empNo;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlt = fechaAlt;
       this.salario = salario;
       this.comision = comision;
       this.deptNo = deptNo;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Short getDir() {
        return this.dir;
    }
    
    public void setDir(Short dir) {
        this.dir = dir;
    }
    public Date getFechaAlt() {
        return this.fechaAlt;
    }
    
    public void setFechaAlt(Date fechaAlt) {
        this.fechaAlt = fechaAlt;
    }
    public Long getSalario() {
        return this.salario;
    }
    
    public void setSalario(Long salario) {
        this.salario = salario;
    }
    public Long getComision() {
        return this.comision;
    }
    
    public void setComision(Long comision) {
        this.comision = comision;
    }
    public Byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(Byte deptNo) {
        this.deptNo = deptNo;
    }




}


