package clases;
// Generated 25-mar-2014 9:05:28 by Hibernate Tools 3.6.0



/**
 * Datosempleados generated by hbm2java
 */
public class Datosempleados  implements java.io.Serializable {


     private DatosempleadosId id;

    public Datosempleados() {
    }

    public Datosempleados(DatosempleadosId id) {
       this.id = id;
    }
   
    public DatosempleadosId getId() {
        return this.id;
    }
    
    public void setId(DatosempleadosId id) {
        this.id = id;
    }




}


